export const PROMPT_SUGGESTIONS = [
  'high quality',
  'best quality',
  'masterpiece',
  'sharp focus',
  'highly detailed',
  'cinematic lighting',
  'soft light',
  'dramatic light',
  'volumetric light',
  'ambient light',
  '8k',
  'ultra detailed',
  'photo realistic',
  'digital art',
  'concept art',
  'studio lighting',
  'depth of field',
  'film grain',
  'portrait',
  'landscape',
  'wide angle',
  'close up',
  'bokeh',
  'vibrant colors',
  'soft shadows',
  'sharp shadows',
]
